language: python

python:
          - "3.5"
          - "3.6-dev"

install:
          - pip install -r test-requirements.txt
          - pip install -r requirements.txt

script: 
  - python3 -m pytest --cov-report term-missing --cov chubby
