language: python

python:
  - "3.5"
  - "3.6-dev"

install:
  - pip install -r test-requirements.txt
  - pip install -r requirements.txt

script:
  - python3 -m pytest --cov-report term-missing --cov chubby
  - sh -c 'if [[ $TRAVIS_PULL_REQUEST -ne true]] && [[ $TRAVIS_BRANCH -ne "master"]]; then ./ci./deploy.pypi.sh; else exit 0;fi'
